"""Karaoke prompt sets — sentences to read aloud (roadmap #21).

Giving someone a sentence to read ("karaoke") is the fastest way to collect
clean, *labelled* audio: the prompt IS the transcript, so the Check step has a
ground truth to compare against. We ship a small, CC0 / public-domain starter set
per language here; the full product seeds these from the Common Voice CC0 sentence
corpus (see project/docs/PROMPTS.md). All sentences here are short, clear, and
phonetically varied. Each language's set is written **in that language** — the
benchmark and the wizard always read prompts in the chosen language.
"""

from __future__ import annotations

# CC0 (public-domain dedication) — original, intentionally simple sentences.
PROMPT_SETS: dict[str, list[str]] = {
    "af": [
        "Die kat het op die warm mat gesit.",
        "Ek hou van hardloop en spring en speel.",
        "Kyk na die groot blou lug vandag.",
        "My hond kan 'n klein balletjie vang.",
        "Ons eet rooi appels na middagete.",
        "Die maan is helder en rond in die nag.",
        "Gee my asseblief die groen koppie.",
        "Voëls sing 'n vrolike liedjie elke oggend.",
        "Sy het 'n geel son en 'n boom geteken.",
        "Kom ons lees nou 'n prettige storie.",
        "Die trein gaan vinnig langs die spoor.",
        "Ek kan baie vinnig tot tien tel.",
    ],
    "am": [
        "ድመቷ በሞቀ ምንጣፍ ላይ ተቀመጠ።",
        "መሮጥ፣ መዝለል እና መጫወት እወዳለሁ።",
        "ዛሬ ትልቁን ሰማያዊ ሰማይ ተመልከት።",
        "ውሻዬ ትንሽ ኳስ መያዝ ይችላል።",
        "ከምሳ በኋላ ቀይ ፖም እንበላለን።",
        "ጨረቃ ምሽት ላይ ብሩህና ክብ ነች።",
        "እባክህ አረንጓዴ ኩባያ ስጠኝ።",
        "ወፎች በየጠዋቱ ደስ የሚያሰኝ ዘፈን ይዘፍናሉ።",
        "ቢጫ ፀሐይና ዛፍ ሳለች።",
        "አሁን አስደሳች ታሪክ እናንብብ።",
        "ባቡር ሐዲዱ ላይ በፍጥነት ይሄዳል።",
        "በጣም በፍጥነት እስከ አስር መቁጠር እችላለሁ።",
    ],
    "ar": [
        "جلست القطة على الحصيرة الدافئة.",
        "أحب الجري والقفز واللعب.",
        "انظر إلى السماء الزرقاء الكبيرة اليوم.",
        "يستطيع كلبي الإمساك بكرة صغيرة.",
        "نأكل التفاح الأحمر بعد الغداء.",
        "القمر مضيء ومستدير في الليل.",
        "من فضلك ناولني الكوب الأخضر.",
        "تغني الطيور أغنية سعيدة كل صباح.",
        "رسمت شمسًا صفراء وشجرة.",
        "لنقرأ الآن قصة ممتعة.",
        "القطار يسير بسرعة على القضبان.",
        "أستطيع العد حتى عشرة بسرعة كبيرة.",
    ],
    "as": [
        "মেকুৰীটো গৰম পাটিৰ ওপৰত বহিছিল।",
        "মই দৌৰিবলৈ, জঁপিয়াবলৈ আৰু খেলিবলৈ ভাল পাওঁ।",
        "আজি ডাঙৰ নীলা আকাশখনৰ দিশে চোৱা।",
        "মোৰ কুকুৰে এটা সৰু বল ধৰিব পাৰে।",
        "আমি দুপৰীয়াৰ আহাৰৰ পিছত ৰঙা আপেল খাওঁ।",
        "ৰাতি চন্দ্ৰ উজ্জ্বল আৰু ঘূৰণীয়া।",
        "অনুগ্ৰহ কৰি মোক সেউজীয়া কাপটো দিয়া।",
        "পুৱাতে চৰাইবোৰে সুখী গান গায়।",
        "তাই এটা হালধীয়া সূৰ্য আৰু এজোপা গছ আঁকিলে।",
        "এতিয়া আমি এটা মজাৰ গল্প পঢ়ো।",
        "ৰেলগাড়ীখন ৰেলপথেদি খুব দ্ৰুতভাৱে যায়।",
        "মই দহলৈকে খুব দ্ৰুতভাৱে গণনা কৰিব পাৰো।",
    ],
    "az": [
        "Pişik isti xalça üstündə oturdu.",
        "Mən qaçmağı, tullanmağı və oynamağı sevirəm.",
        "Bu gün böyük mavi göyə bax.",
        "Mənim itim kiçik bir topu tuta bilər.",
        "Biz nahardan sonra qırmızı alma yeyirik.",
        "Gecə ay parlaq və dəyirmidir.",
        "Zəhmət olmasa, mənə yaşıl fincanı ver.",
        "Quşlar hər səhər şən bir mahnı oxuyur.",
        "O, sarı bir günəş və bir ağac çəkdi.",
        "Gəlin indi maraqlı bir hekayə oxuyaq.",
        "Qatar relslərlə sürətlə gedir.",
        "Mən çox sürətlə ona qədər saya bilərəm.",
    ],
    "ba": [
        "Мысыҡ йылы келәмдә ултырҙы.",
        "Мин йүгерергә, һикерергә һәм уйнарға яратам.",
        "Бөгөн ҙур зәңгәр күккә ҡара.",
        "Минең этем бәләкәй туп тота ала.",
        "Без төшкө ашҡан һуң ҡыҙыл алмалар ашайбыҙ.",
        "Төндә ай яҡты һәм тулы.",
        "Зинһар, миңә йәшел кружканы бирегеҙ.",
        "Ҡоштар иртә һайын шат йыр йырлай.",
        "Ул һары ҡояш һәм ағас рәсемен яһаны.",
        "Беҙ хәҙер ҡыҙыҡлы хикәйә уҡыйыҡ.",
        "Поезд рельс буйлап тиҙ бара.",
        "Мин унға тиклем бик тиҙ иҫәпләй алам.",
    ],
    "be": [
        "Кот сядзеў на цёплым дыванку.",
        "Я люблю бегаць, скакаць і гуляць.",
        "Паглядзі на вялікае блакітнае неба сёння.",
        "Мой сабака можа злавіць маленькі мячык.",
        "Мы ядзім чырвоныя яблыкі пасля абеду.",
        "Месяц яркі і круглы ноччу.",
        "Калі ласка, падай мне зялёную кружку.",
        "Птушкі кожную раніцу спяваюць вясёлую песню.",
        "Яна намалявала жоўтае сонца і дрэва.",
        "Давайце пачытаем цікавую казку зараз.",
        "Цягнік хутка едзе па рэйках.",
        "Я магу вельмі хутка лічыць да дзесяці.",
    ],
    "bg": [
        "Котката седеше на топлата постелка.",
        "Обичам да тичам, скачам и играя.",
        "Погледни голямото синьо небе днес.",
        "Кучето ми може да хване малка топка.",
        "Ядем червени ябълки след обяд.",
        "Луната е ярка и кръгла нощем.",
        "Моля, подай ми зелената чаша.",
        "Птиците пеят весела песен всяка сутрин.",
        "Тя нарисува жълто слънце и дърво.",
        "Нека прочетем забавна история сега.",
        "Влакът се движи бързо по релсите.",
        "Мога да броя до десет много бързо.",
    ],
    "bn": [
        "বিড়ালটি উষ্ণ চাটাইয়ে বসেছিল।",
        "আমি দৌড়াতে, লাফাতে এবং খেলতে ভালোবাসি।",
        "আজ বড় নীল আকাশের দিকে তাকাও।",
        "আমার কুকুর একটি ছোট বল ধরতে পারে।",
        "আমরা দুপুরের খাবারের পর লাল আপেল খাই।",
        "রাতে চাঁদ উজ্জ্বল এবং গোল।",
        "দয়া করে আমাকে সবুজ কাপটা দাও।",
        "পাখিরা প্রতি সকালে একটি আনন্দের গান গায়।",
        "সে একটি হলুদ সূর্য এবং একটি গাছ আঁকল।",
        "চলো এখন একটি মজার গল্প পড়ি।",
        "ট্রেনটি ট্র্যাকে দ্রুত ছুটে যায়।",
        "আমি খুব দ্রুত দশ পর্যন্ত গণনা করতে পারি।",
    ],
    "bo": [
        "ཞི་མི་དྲོ་བའི་གདན་གྱི་སྟེང་དུ་འདུག",
        "ང་རྒྱུགས་ནས་མཆོང་ནས་རྩེད་མོ་རྩེ་བར་དགའ།",
        "དེ་རིང་ནམ་མཁའ་ཆེན་པོ་སྔོན་པོ་ལ་ལྟོས།",
        "ངའི་ཁྱི་ཡིས་རིལ་བུ་ཆུང་ཆུང་ཞིག་འཛིན་ཐུབ།",
        "ང་ཚོས་ཉིན་གུང་རྗེས་སུ་ཀུ་ཤུ་དམར་པོ་ཟ།",
        "ཟླ་བ་མཚན་མོར་གསལ་ཞིང་ཟླུམ་པོར་གནས།",
        "ལྗང་ཁུའི་ཕོར་པ་ཅིག་ངར་སྤྲོད་རོགས།",
        "བྱ་ཚོས་ཞོགས་རེར་སྐྱིད་པའི་གླུ་ལེན།",
        "མོས་ཉི་མ་སེར་པོ་དང་ཤིང་ཅིག་བྲིས།",
        "ད་ལྟ་ང་ཚོས་སྒྲུང་སྤྲོ་བ་ཅིག་ཀློག་ཤོག",
        "མེ་འཁོར་ལྕགས་ལམ་ཐོག་ནས་མྱུར་དུ་འགྲོ།",
        "ང་ཤིན་ཏུ་མྱུར་དུ་བཅུ་བར་གྲངས་འབོར་བྱེད་ཐུབ།",
    ],
    "br": [
        "Ar c'hazh a azezas war ar tapis tomm.",
        "Kaout a ran plijadur da redek, lammat ha c'hoari.",
        "Sell ouzh an oabl bras glas hiziv.",
        "Ma c'hi a c'hell kemer ur boulenn vihan.",
        "Ni a zebr avaloù ruz goude al lein.",
        "Ar loar a zo sklaer ha krenn d'an noz.",
        "Mar plij, reit din ar gopenn c'hlas.",
        "Ar evned a gan ur ganaouenn laouen bep mintin.",
        "Hi a tynnas un heol melen hag ur wezenn.",
        "Lenn a raimp un istor diverjus bremañ.",
        "Ar tren a ya buan war an hent-houarn.",
        "Gallout a ran kontañ betek dek kalz buan.",
    ],
    "bs": [
        "Mačka je sjela na toplu podlogu.",
        "Volim trčati, skakati i igrati se.",
        "Pogledaj veliko plavo nebo danas.",
        "Moj pas može uhvatiti malu loptu.",
        "Jedemo crvene jabuke nakon ručka.",
        "Mjesec je sjajan i okrugao noću.",
        "Molim te dodaj mi zelenu šolju.",
        "Ptice pjevaju veselu pjesmu svako jutro.",
        "Nacrtala je žuto sunce i drvo.",
        "Hajde da čitamo zabavnu priču sada.",
        "Voz ide brzo niz prugu.",
        "Mogu da brojim do deset veoma brzo.",
    ],
    "ca": [
        "El gat va seure a l'estora calenta.",
        "M'agrada córrer, saltar i jugar.",
        "Mira el gran cel blau d'avui.",
        "El meu gos pot agafar una pilota petita.",
        "Mengem pomes vermelles després de dinar.",
        "A la nit, la lluna és brillant i rodona.",
        "Si us plau, passa'm la tassa verda.",
        "Els ocells canten una cançó alegre cada matí.",
        "Va dibuixar un sol groc i un arbre.",
        "Llegim una història divertida ara.",
        "El tren va ràpid per la via.",
        "Puc comptar fins a deu molt ràpid.",
    ],
    "cs": [
        "Kočka seděla na teplé podložce.",
        "Rád běhám, skáču a hraju si.",
        "Podívej se dnes na velkou modrou oblohu.",
        "Můj pes dokáže chytit malý míček.",
        "Po obědě jíme červená jablka.",
        "V noci je měsíc jasný a kulatý.",
        "Podej mi prosím zelený hrnek.",
        "Ptáci každé ráno zpívají veselou píseň.",
        "Nakreslila žluté slunce a strom.",
        "Pojďme si teď přečíst zábavný příběh.",
        "Vlak jede rychle po kolejích.",
        "Umím počítat do deseti velmi rychle.",
    ],
    "cy": [
        "Eisteddodd y gath ar y mat cynnes.",
        "Rwy'n hoffi rhedeg a neidio a chwarae.",
        "Edrych ar yr awyr las fawr heddiw.",
        "Gall fy nghi ddal pêl fach.",
        "Rydyn ni'n bwyta afalau coch ar ôl cinio.",
        "Mae'r lleuad yn llachar ac yn grwn gyda'r nos.",
        "Pasiwch y cwpan gwyrdd i mi, os gwelwch yn dda.",
        "Mae adar yn canu cân hapus bob bore.",
        "Tynnodd hi haul melyn a choeden.",
        "Gadewch i ni ddarllen stori hwyl nawr.",
        "Mae'r trên yn mynd yn gyflym ar hyd y trac.",
        "Gallaf gyfrif i ddeg yn gyflym iawn.",
    ],
    "da": [
        "Katten sad på den varme måtte.",
        "Jeg kan lide at løbe, hoppe og lege.",
        "Se på den store blå himmel i dag.",
        "Min hund kan fange en lille bold.",
        "Vi spiser røde æbler efter frokost.",
        "Månen er lys og rund om natten.",
        "Vil du give mig den grønne kop?",
        "Fugle synger en glad sang hver morgen.",
        "Hun tegnede en gul sol og et træ.",
        "Lad os læse en sjov historie nu.",
        "Toget kører hurtigt ned ad sporet.",
        "Jeg kan tælle til ti meget hurtigt.",
    ],
    "de": [
        "Die Katze sitzt auf der Matte.",
        "Ich laufe und springe gern.",
        "Schau dir den blauen Himmel an.",
        "Mein Hund fängt den kleinen Ball.",
        "Wir essen mittags rote Äpfel.",
        "Der Mond scheint hell in der Nacht.",
        "Bitte gib mir die grüne Tasse.",
        "Die Vögel singen jeden Morgen ein fröhliches Lied.",
        "Sie zeichnete eine gelbe Sonne und einen Baum.",
        "Lass uns jetzt eine lustige Geschichte lesen.",
        "Der Zug fährt schnell auf den Gleisen.",
        "Ich kann sehr schnell bis zehn zählen.",
    ],
    "el": [
        "Η γάτα κάθισε στο ζεστό χαλί.",
        "Μου αρέσει να τρέχω, να πηδώ και να παίζω.",
        "Κοίτα τον μεγάλο γαλάζιο ουρανό σήμερα.",
        "Ο σκύλος μου μπορεί να πιάσει μια μικρή μπάλα.",
        "Τρώμε κόκκινα μήλα μετά το μεσημεριανό.",
        "Το φεγγάρι είναι φωτεινό και στρογγυλό τη νύχτα.",
        "Παρακαλώ δώσε μου το πράσινο φλιτζάνι.",
        "Τα πουλιά τραγουδούν ένα χαρούμενο τραγούδι κάθε πρωί.",
        "Ζωγράφισε έναν κίτρινο ήλιο και ένα δέντρο.",
        "Ας διαβάσουμε μια διασκεδαστική ιστορία τώρα.",
        "Το τρένο πηγαίνει γρήγορα κατά μήκος της γραμμής.",
        "Μπορώ να μετρήσω μέχρι το δέκα πολύ γρήγορα.",
    ],
    "en": [
        "The cat sat on the warm mat.",
        "I like to run and jump and play.",
        "Look at the big blue sky today.",
        "My dog can catch a little ball.",
        "We eat red apples after lunch.",
        "The moon is bright and round at night.",
        "Please pass me the green cup.",
        "Birds sing a happy song each morning.",
        "She drew a yellow sun and a tree.",
        "Let us read a fun story now.",
        "The train goes fast down the track.",
        "I can count to ten very fast.",
    ],
    "es": [
        "El gato está en la alfombra tibia.",
        "Me gusta correr, saltar y jugar.",
        "Mira el gran cielo azul de hoy.",
        "Mi perro puede atrapar una pelota pequeña.",
        "Comemos manzanas rojas después del almuerzo.",
        "La luna está brillante y redonda por la noche.",
        "Por favor, pásame la taza verde.",
        "Los pájaros cantan una canción alegre cada mañana.",
        "Ella dibujó un sol amarillo y un árbol.",
        "Leamos una historia divertida ahora.",
        "El tren va rápido por la vía.",
        "Puedo contar hasta diez muy rápido.",
    ],
    "et": [
        "Kass istus soojal matil.",
        "Mulle meeldib joosta, hüpata ja mängida.",
        "Vaata täna suurt sinist taevast.",
        "Mu koer suudab väikese palli püüda.",
        "Sööme pärast lõunat punaseid õunu.",
        "Öösiti on kuu hele ja ümmargune.",
        "Palun anna mulle roheline tass.",
        "Linnud laulavad igal hommikul rõõmsat laulu.",
        "Ta joonistas kollase päikese ja puu.",
        "Loeme nüüd üht lõbusat lugu.",
        "Rong sõidab rajal kiiresti.",
        "Ma oskan kümneni väga kiiresti loendada.",
    ],
    "eu": [
        "Katua tapete epelaren gainean eseri zen.",
        "Gustuko dut korrika egin, jauzi egin eta jolastea.",
        "Begira iezaiozu gaur zeru urdin zabalari.",
        "Nire txakurrak pilota txiki bat harrap dezake.",
        "Bazkariaren ondoren sagar gorriak jaten ditugu.",
        "Gauez ilargia argi eta biribila da.",
        "Mesedez, eman iezadazu edalontzi berdea.",
        "Txoriek goiz bakoitzean abesti alai bat abesten dute.",
        "Eguzki hori eta zuhaitz bat marraztu zituen.",
        "Irakur dezagun orain ipuin dibertigarri bat.",
        "Trena trenbidean azkar doa.",
        "Hamar arte oso azkar zenbatu dezaket.",
    ],
    "fa": [
        "گربه روی حصیر گرم نشست.",
        "من دوست دارم بدوم، بپرم و بازی کنم.",
        "امروز به آسمان آبی بزرگ نگاه کن.",
        "سگ من می‌تواند یک توپ کوچک بگیرد.",
        "ما بعد از ناهار سیب‌های قرمز می‌خوریم.",
        "ماه در شب روشن و گرد است.",
        "لطفاً فنجان سبز را به من بده.",
        "پرندگان هر صبح یک آهنگ شاد می‌خوانند.",
        "او یک خورشید زرد و یک درخت کشید.",
        "بیایید یک داستان جالب بخوانیم.",
        "قطار روی ریل‌ها تند می‌رود.",
        "من می‌توانم خیلی سریع تا ده بشمارم.",
    ],
    "fi": [
        "Kissa istui lämpimällä matolla.",
        "Pidän juoksemisesta, hyppimisestä ja leikkimisestä.",
        "Katso, kuinka suuri ja sininen taivas on tänään.",
        "Koirani osaa napata pienen pallon.",
        "Syömme punaisia omenoita lounaan jälkeen.",
        "Kuu on kirkas ja pyöreä yöllä.",
        "Antaisitko minulle vihreän kupin?",
        "Linnut laulavat iloista laulua joka aamu.",
        "Hän piirsi keltaisen auringon ja puun.",
        "Luetaan nyt hauska tarina.",
        "Juna kulkee nopeasti pitkin raidetta.",
        "Osaan laskea kymmeneen todella nopeasti.",
    ],
    "fo": [
        "Køtturin sat á varma mottuni.",
        "Eg elski at renna og hoppa og leika.",
        "Kík á tann stóra bláa himininn í dag.",
        "Hundur mín kann fanga ein lítlan bøll.",
        "Vit eta reyðar epli eftir miðdagsmat.",
        "Máni er ljós og kringlóttur um náttina.",
        "Ger so væl at geva mær grøna koppin.",
        "Fuglar syngja eina glaða søng hvønn morgun.",
        "Hon teiknaði gula sól og eitt træ.",
        "Lat okkum lesa eina skemtisøgu nú.",
        "Tógið fer skjótt niður sporin.",
        "Eg kann telja til tíggju mjøg skjótt.",
    ],
    "fr": [
        "Le chat est assis sur le tapis.",
        "J'aime courir, sauter et jouer.",
        "Regarde le grand ciel bleu aujourd'hui.",
        "Mon chien attrape la petite balle.",
        "Nous mangeons des pommes rouges à midi.",
        "La lune est brillante et ronde la nuit.",
        "Passe-moi la tasse verte, s'il te plaît.",
        "Les oiseaux chantent une chanson joyeuse chaque matin.",
        "Elle a dessiné un soleil jaune et un arbre.",
        "Lisons une histoire amusante maintenant.",
        "Le train va vite sur les rails.",
        "Je peux compter jusqu'à dix très vite.",
    ],
    "gl": [
        "O gato sentouse na alfombra quente.",
        "Gústame correr, saltar e xogar.",
        "Mira o gran ceo azul de hoxe.",
        "O meu can pode coller unha pelota pequena.",
        "Comemos mazás vermellas despois do xantar.",
        "A lúa é brillante e redonda pola noite.",
        "Por favor, pásame a cunca verde.",
        "Os paxaros cantan unha canción alegre cada mañá.",
        "Ela debuxou un sol amarelo e unha árbore.",
        "Imos ler un conto divertido agora.",
        "O tren vai rápido pola vía.",
        "Podo contar ata dez moi rápido.",
    ],
    "gu": [
        "બિલાડી ગરમ સાદડી પર બેઠી.",
        "મને દોડવું, કૂદવું અને રમવું ગમે છે.",
        "આજે મોટા વાદળી આકાશ ને જુઓ.",
        "મારો કૂતરો નાની દડી પકડી શકે છે.",
        "આપણે બપોર પછી લાલ સફરજન ખાઈએ છીએ.",
        "ચાંદ રાત્રે ઉજ્જ્વળ અને ગોળ છે.",
        "કૃપા કરીને મને લીલો કપ આપો.",
        "પ્રત્યેક સવારે પક્ષીઓ ખુશ ગીત ગાય છે.",
        "તેણે એક પીળો સૂરજ અને ઝાડ દોર્યાં.",
        "ચાલો હવે એક મઝાની વાર્તા વાંચીએ.",
        "ટ્રેન પાટા પર ઝડપથી જાય છે.",
        "હું ખૂબ ઝડપથી દસ સુધી ગણી શકું છું.",
    ],
    "ha": [
        "Kyanwa ta zauna a kan tabarmar dumi.",
        "Ina son gudu, tsalle da wasa.",
        "Duba babban sama mai shudi a yau.",
        "Kare na zai iya kama ƙaramin ƙwallo.",
        "Muna cin jan tuffa bayan abincin rana.",
        "Wata tana haskakawa kuma zagaye da dare.",
        "Don Allah ka ba ni kofin kore.",
        "Tsuntsaye suna waƙar farin ciki duk safe.",
        "Ta zana rana mai rawaya da bishiya.",
        "Bari mu karanta labari mai daɗi yanzu.",
        "Jirgin ƙasa yana tafiya da sauri a kan layi.",
        "Ina iya ƙidaya zuwa goma da sauri sosai.",
    ],
    "haw": [
        "Noho ka pōpoki ma luna o ke moena pumehana.",
        "Makemake au e holo, e lele, a e pāʻani.",
        "E nānā i ke aouli nui ʻuliʻuli o kēia lā.",
        "Hiki i koʻu ʻīlio ke hopu i ka kinipōpō liʻiliʻi.",
        "ʻAi mākou i nā ʻāpala ʻulaʻula ma hope o ke awakea.",
        "ʻŌlinolino a poepoe ka mahina i ka pō.",
        "E ʻoluʻolu, e hāʻawi mai iaʻu i ke kīʻaha ʻōmaʻomaʻo.",
        "Mele nā manu i ka himeni hauʻoli i kēlā kēia kakahiaka.",
        "Kaha ʻo ia i ka lā melemele a me ka lāʻau.",
        "E heluhelu kākou i kahi moʻolelo leʻaleʻa i kēia manawa.",
        "Holo wikiwiki ka kaʻaahi ma ke alanui hao.",
        "Hiki iaʻu ke helu a ʻumi me ka wikiwiki.",
    ],
    "he": [
        "החתול ישב על השטיח החמים.",
        "אני אוהב לרוץ, לקפוץ ולשחק.",
        "תסתכל על השמיים הגדולים והכחולים היום.",
        "הכלב שלי יכול לתפוס כדור קטן.",
        "אנחנו אוכלים תפוחים אדומים אחרי הצהריים.",
        "הירח בהיר ועגול בלילה.",
        "בבקשה תעביר לי את הכוס הירוקה.",
        "הציפורים שרות שיר שמח כל בוקר.",
        "היא ציירה שמש צהובה ועץ.",
        "בואו נקרא סיפור כיף עכשיו.",
        "הרכבת נוסעת מהר על הפסים.",
        "אני יכול לספור עד עשר מהר מאוד.",
    ],
    "hi": [
        "बिल्ली गर्म चटाई पर बैठी।",
        "मुझे दौड़ना, कूदना और खेलना पसंद है।",
        "आज आसमान कितना बड़ा और नीला है!",
        "मेरा कुत्ता एक छोटी गेंद पकड़ सकता है।",
        "हम दोपहर के खाने के बाद लाल सेब खाते हैं।",
        "रात में चाँद चमकीला और गोल होता है।",
        "कृपया मुझे हरा कप दीजिए।",
        "पक्षी हर सुबह एक खुशनुमा गाना गाते हैं।",
        "उसने एक पीला सूरज और एक पेड़ बनाया।",
        "चलो अभी एक मज़ेदार कहानी पढ़ते हैं।",
        "ट्रेन पटरी पर तेज़ दौड़ती है।",
        "मैं बहुत तेज़ी से दस तक गिन सकता हूँ।",
    ],
    "hr": [
        "Mačka je sjedila na toploj prostirci.",
        "Volim trčati, skakati i igrati se.",
        "Pogledaj veliko plavo nebo danas.",
        "Moj pas može uhvatiti malu loptu.",
        "Jedemo crvene jabuke nakon ručka.",
        "Mjesec je sjajan i okrugao noću.",
        "Molim te, dodaj mi zelenu šalicu.",
        "Ptice pjevaju veselu pjesmu svako jutro.",
        "Ona je nacrtala žuto sunce i drvo.",
        "Hajde da pročitamo zabavnu priču sada.",
        "Vlak ide brzo niz prugu.",
        "Mogu izbrojati do deset vrlo brzo.",
    ],
    "ht": [
        "Chat la te chita sou natt cho a.",
        "Mwen renmen kouri ak sote ak jwe.",
        "Gade gwo syèl ble a jodi a.",
        "Chen mwen ka atrape yon ti boul.",
        "Nou manje pòm wouj apre dine.",
        "Lalin lan klè e won nan lannwit.",
        "Tanpri pase m gode vèt la.",
        "Zwazo yo chante yon bèl chante chak maten.",
        "Li desine yon solèy jòn ak yon pyebwa.",
        "Ann li yon istwa amizan kounye a.",
        "Tren an ale vit sou pis la.",
        "Mwen ka konte jiska dis trè vit.",
    ],
    "hu": [
        "A macska a meleg szőnyegen ül.",
        "Szeretek futni, ugrálni és játszani.",
        "Nézd a nagy kék eget ma!",
        "A kutyám elkapja a kis labdát.",
        "Ebéd után piros almát eszünk.",
        "A hold fényes és kerek éjjel.",
        "Kérlek, add ide a zöld poharat.",
        "A madarak minden reggel vidám dalt énekelnek.",
        "Rajzolt egy sárga napot és egy fát.",
        "Olvassunk most egy vidám mesét.",
        "A vonat gyorsan halad a sínen.",
        "Tízig nagyon gyorsan tudok számolni.",
    ],
    "hy": [
        "Կատուն նստեց տաք գորգի վրա։",
        "Ես սիրում եմ վազել, ցատկել և խաղալ։",
        "Այսօր նայիր մեծ կապույտ երկնքին։",
        "Իմ շունը կարող է բռնել փոքր գնդակ։",
        "Ճաշից հետո ուտում ենք կարմիր խնձոր։",
        "Գիշերը լուսինը պայծառ և կլոր է։",
        "Խնդրում եմ, տուր ինձ կանաչ բաժակը։",
        "Թռչունները ամեն առավոտ ուրախ երգ են երգում։",
        "Նա նկարեց դեղին արեւ ու ծառ։",
        "Հիմա կարդանք մի զվարճալի պատմություն։",
        "Գնացքն արագ է գնում ռելսերի վրայով։",
        "Ես կարող եմ շատ արագ հաշվել մինչև տաս։",
    ],
    "id": [
        "Kucing itu duduk di atas karpet yang hangat.",
        "Aku suka berlari, melompat, dan bermain.",
        "Lihat langit biru yang luas hari ini.",
        "Anjingku bisa menangkap bola kecil.",
        "Kami makan apel merah setelah makan siang.",
        "Bulan terlihat terang dan bulat di malam hari.",
        "Tolong berikan aku cangkir hijau itu.",
        "Burung-burung bernyanyi dengan riang setiap pagi.",
        "Dia menggambar matahari kuning dan sebatang pohon.",
        "Mari kita baca cerita yang menyenangkan sekarang.",
        "Kereta melaju cepat di sepanjang rel.",
        "Aku bisa menghitung sampai sepuluh dengan sangat cepat.",
    ],
    "is": [
        "Kötturinn sat á hlýja mottunni.",
        "Mér líður vel að hlaupa, hoppa og leika.",
        "Lítu á hinn stóra bláa himininn í dag.",
        "Hundur minn getur náð í lítinn bolta.",
        "Við borðum rauð epli eftir hádegismat.",
        "Tunglið er bjart og kringlótt á nóttunni.",
        "Gjörðu svo vel og rétt mér græna bollann.",
        "Fuglar syngja glæsilega söng á hverjum morgni.",
        "Hún teiknaði gula sól og tré.",
        "Við skulum lesa skemmtilega sögu núna.",
        "Lestin fer hratt eftir brautinni.",
        "Ég get talið mjög hratt upp í tíu.",
    ],
    "it": [
        "Il gatto è seduto sul tappeto caldo.",
        "Mi piace correre, saltare e giocare.",
        "Guarda il grande cielo blu oggi.",
        "Il mio cane prende la piccola palla.",
        "Mangiamo mele rosse dopo pranzo.",
        "La luna luminosa e tonda splende di notte.",
        "Per favore, passami la tazza verde.",
        "Gli uccelli cantano una canzone allegra ogni mattina.",
        "Lei ha disegnato un sole giallo e un albero.",
        "Leggiamo una storia divertente adesso.",
        "Il treno va veloce lungo il binario.",
        "Riesco a contare fino a dieci molto velocemente.",
    ],
    "ja": [
        "猫が暖かいマットの上に座りました。",
        "私は走ったり、跳んだり、遊んだりするのが好きです。",
        "今日は大きな青い空を見てください。",
        "私の犬は小さなボールをキャッチできます。",
        "私たちはお昼の後に赤いリンゴを食べます。",
        "夜、月は明るく丸いです。",
        "緑のカップを渡してください。",
        "鳥たちは毎朝楽しい歌を歌います。",
        "彼女は黄色い太陽と木を描きました。",
        "今、楽しいお話を読みましょう。",
        "電車は線路を速く走ります。",
        "私はとても速く十まで数えられます。",
    ],
    "jw": [
        "Kucing lungguh ing klasa sing anget.",
        "Aku seneng mlayu, mloncat, lan dolanan.",
        "Delokna langit biru sing gedhe dina iki.",
        "Anjingku bisa nyekel bal cilik.",
        "Kita mangan apel abang sawise makan awan.",
        "Rembulan padhang lan bunder ing wengi.",
        "Tulung wenehna aku cangkir ijo.",
        "Manuk-manuk nembang tembang bungah saben esuk.",
        "Dheweke nggambar srengenge kuning lan wit-witan.",
        "Ayo maca crita nyenengake saiki.",
        "Sepur mlaku banter ing rel.",
        "Aku bisa ngitung nganti sepuluh kanthi cepet.",
    ],
    "ka": [
        "კატა თბილ ხალიჩაზე ჯდა.",
        "მე მიყვარს სირბილი, ხტომა და თამაში.",
        "დახედე დღეს დიდ ლურჯ ცას.",
        "ჩემს ძაღლს შეუძლია პატარა ბურთი დაიჭიროს.",
        "ჩვენ სადილის შემდეგ წითელ ვაშლებს ვჭამთ.",
        "ღამით მთვარე კაშკაშაა და მრგვალია.",
        "გთხოვ, მომეციე მწვანე ჭიქა.",
        "ჩიტები ყოველ დილით ბედნიერ სიმღერას მღერიან.",
        "მან ყვითელი მზე და ხე დახატა.",
        "მოდი, ახლა სახალისო ამბავი წავიკითხოთ.",
        "მატარებელი სწრაფად მიდის რელსებზე.",
        "შემიძლია ძალიან სწრაფად ათამდე დავთვალო.",
    ],
    "kk": [
        "Мысық жылы кілемшенің үстінде отырды.",
        "Мен жүгіруді, секіруді және ойнауды ұнатамын.",
        "Бүгін үлкен көк аспанға қара.",
        "Менің итім кішкентай допты ұстай алады.",
        "Біз түскі астан кейін қызыл алма жейміз.",
        "Түнде ай жарық және дөңгелек.",
        "Маған жасыл кесені беріңізші.",
        "Құстар әр таңда қуанышты ән салады.",
        "Ол сары күн мен ағаш салды.",
        "Қазір қызықты ертегі оқыйық.",
        "Пойыз жолмен жылдам жүреді.",
        "Мен өте жылдам онға дейін санай аламын.",
    ],
    "km": [
        "ឆ្មាអង្គុយលើព្រំក្តៅ។",
        "ខ្ញុំចូលចិត្តរត់ លោត និងលេង។",
        "មើលមេឃធំៗពណ៌ខៀវថ្ងៃនេះ។",
        "ឆ្កែរបស់ខ្ញុំអាចចាប់បាល់តូចបាន។",
        "យើងញ៉ាំប៉ោមក្រហមក្រោយអាហារថ្ងៃត្រង់។",
        "ព្រះច័ន្ទភ្លឺ និងមូលនៅពេលយប់។",
        "សូមមេត្តាប្រគល់ពែងពណ៌បៃតងមកខ្ញុំ។",
        "សត្វបក្សីច្រៀងចំរៀងរីករាយរៀងរាល់ព្រឹក។",
        "នាងគូររូបព្រះអាទិត្យពណ៌លឿង និងដើមឈើ។",
        "តោះយើងអានរឿងសប្បាយឥឡូវនេះ។",
        "រថភ្លើងដំណើរលឿននៅលើផ្លូវ។",
        "ខ្ញុំអាចរាប់ដល់ដប់បានលឿនណាស់។",
    ],
    "kn": [
        "ಬೆಕ್ಕು ಬೆಚ್ಚನೆಯ ಚಾಪೆಯ ಮೇಲೆ ಕುಳಿತಿತು.",
        "ನಾನು ಓಡಲು, ಜಿಗಿಯಲು ಮತ್ತು ಆಡಲು ಇಷ್ಟಪಡುತ್ತೇನೆ.",
        "ಇಂದು ದೊಡ್ಡ ನೀಲಿ ಆಕಾಶವನ್ನು ನೋಡು.",
        "ನನ್ನ ನಾಯಿ ಸಣ್ಣ ಚೆಂಡನ್ನು ಹಿಡಿಯಬಲ್ಲದು.",
        "ನಾವು ಊಟದ ನಂತರ ಕೆಂಪು ಸೇಬುಗಳನ್ನು ತಿನ್ನುತ್ತೇವೆ.",
        "ರಾತ್ರಿ ಚಂದ್ರ ಪ್ರಕಾಶಮಾನವಾಗಿ ಮತ್ತು ದುಂಡಾಗಿ ಇರುತ್ತಾನೆ.",
        "ದಯವಿಟ್ಟು ನನಗೆ ಹಸಿರು ಕಪ್ ಕೊಡಿ.",
        "ಪ್ರತಿ ಬೆಳಿಗ್ಗೆ ಹಕ್ಕಿಗಳು ಸಂತೋಷದ ಹಾಡು ಹಾಡುತ್ತವೆ.",
        "ಅವಳು ಹಳದಿ ಸೂರ್ಯ ಮತ್ತು ಮರವನ್ನು ಬಿಡಿಸಿದಳು.",
        "ಈಗ ಒಂದು ಮೋಜಿನ ಕಥೆ ಓದೋಣ.",
        "ರೈಲು ಹಳಿಯ ಮೇಲೆ ವೇಗವಾಗಿ ಚಲಿಸುತ್ತದೆ.",
        "ನಾನು ತುಂಬಾ ವೇಗವಾಗಿ ಹತ್ತರವರೆಗೆ ಎಣಿಸಬಲ್ಲೆ.",
    ],
    "ko": [
        "고양이가 따뜻한 매트 위에 앉았어요.",
        "나는 달리고 점프하고 노는 것을 좋아해요.",
        "오늘 저 넓고 파란 하늘을 보세요.",
        "우리 강아지는 작은 공을 잡을 수 있어요.",
        "우리는 점심 후에 빨간 사과를 먹어요.",
        "밤에 달은 밝고 둥글어요.",
        "초록색 컵을 건네주세요.",
        "새들은 매일 아침 즐거운 노래를 불러요.",
        "그녀는 노란 태양과 나무를 그렸어요.",
        "이제 재미있는 이야기를 읽어요.",
        "기차가 선로를 따라 빠르게 달려요.",
        "나는 아주 빨리 열까지 셀 수 있어요.",
    ],
    "la": [
        "Felis in calido tegete sedit.",
        "Currere et salire et ludere amo.",
        "Aspice magnum caelum caeruleum hodie.",
        "Canis meus pilam parvam capere potest.",
        "Poma rubra post prandium edimus.",
        "Luna noctu clara et rotunda est.",
        "Da mihi, quaeso, poculum viride.",
        "Aves cantum laetum quoque mane canunt.",
        "Illa solem flavum et arborem pinxit.",
        "Nunc fabulam iucundam legamus.",
        "Currus ferreus celeriter per viam ferream it.",
        "Ad decem numerare celerrime possum.",
    ],
    "lb": [
        "D'Kaz huet op der waarmer Matte gesat.",
        "Ech lafen, sprangen a spillen gär.",
        "Kuck haut de grousse blo Himmel un!",
        "Mäi Hond kann e klenge Ball fänken.",
        "No dem Mëttegiessen iessen mir rout Äppel.",
        "De Mound ass nuets hell a rund.",
        "Gëff mir wannechgelift d'gréng Taass.",
        "Vulleken sangen all Moien e fréilecht Lidd.",
        "Si huet eng giel Sonn an e Bam gezeechent.",
        "Komm, mir liesen elo eng flott Geschicht!",
        "Den Zuch fiert séier iwwert d'Gleise.",
        "Ech kann ganz séier bis zéng zielen.",
    ],
    "ln": [
        "Nsimba afandaki likoló ya etoko ya molunge.",
        "Nalingi kopota, kopumbwa, mpe kosakana.",
        "Lɛlo, tála likoló monene ya langi ya lɛ́mbɛ.",
        "Mbwa na ngai akoki kokanga bɔ́ɔ́lɔ moke.",
        "Tolyaka mapomi ya litatá sima ya bilei ya midi.",
        "Na butu, sanza ezalí polele mpe ya ndéngé ya bɔ́ɔ́lɔ.",
        "Nasengi yo, pesa ngai kopo ya langi ya mpondu.",
        "Bandeke bayimbaka nzembo ya esengo kila tongo.",
        "Ye akomi moyi ya bondobo mpe nzete moko.",
        "Tótánga lisolo ya esengo sikoyo.",
        "Engbunduka ekɛndɛ na mbangu na nzela na yango.",
        "Nakoki kotanga tii na zómi na mbangu mingi.",
    ],
    "lo": [
        "ແມວນັ່ງຢູ່ເທິງເສື່ອອຸ່ນ.",
        "ຂ້ອຍມັກແລ່ນ ແລະ ໂດດ ແລະ ຫຼິ້ນ.",
        "ເບິ່ງທ້ອງຟ້າສີຟ້າກວ້າງໃຫຍ່ໃນມື້ນີ້.",
        "ໝາຂອງຂ້ອຍສາມາດຈັບລູກບານໜ້ອຍໆໄດ້.",
        "ພວກເຮົາກິນໝາກໂປມສີແດງຫຼັງອາຫານທ່ຽງ.",
        "ດວງຈັນສວ່າງ ແລະ ກົມໃນຕອນກາງຄືນ.",
        "ກະລຸນາສົ່ງຈອກສີຂຽວໃຫ້ຂ້ອຍ.",
        "ນົກຮ້ອງເພງດີໃຈທຸກໆເຊົ້າ.",
        "ນາງແຕ້ມດວງອາທິດສີເຫຼືອງ ແລະ ຕົ້ນໄມ້.",
        "ໃຫ້ພວກເຮົາອ່ານນິທານສະໜຸກຕອນນີ້.",
        "ລົດໄຟແລ່ນໄວລົງທາງລາງ.",
        "ຂ້ອຍສາມາດນັບເຖິງສິບໄດ້ໄວຫຼາຍ.",
    ],
    "lt": [
        "Katė sėdėjo ant šilto kilimėlio.",
        "Man patinka bėgioti, šokinėti ir žaisti.",
        "Pažiūrėk į didelį mėlyną dangų šiandien.",
        "Mano šuo gali pagauti mažą kamuolį.",
        "Po pietų valgome raudonus obuolius.",
        "Mėnulis naktį yra ryškus ir apvalus.",
        "Prašau, paduok man žalią puodelį.",
        "Paukščiai kiekvieną rytą dainuoja linksmą dainą.",
        "Ji nupiešė geltoną saulę ir medį.",
        "Paskaitykime linksmą istoriją dabar.",
        "Traukinys greitai važiuoja bėgiais.",
        "Galiu suskaičiuoti iki dešimt labai greitai.",
    ],
    "lv": [
        "Kaķis sēdēja uz silta paklājiņa.",
        "Man patīk skriet, lēkāt un spēlēties.",
        "Paskaties uz lielo zilo debesi šodien.",
        "Mans suns var noķert mazu bumbu.",
        "Mēs ēdam sarkanus ābolus pēc pusdienām.",
        "Naktī mēness ir spilgts un apaļš.",
        "Lūdzu, padod man zaļo krūzi.",
        "Putni katru rītu dzied priecīgu dziesmu.",
        "Viņa uzzīmēja dzeltenu sauli un koku.",
        "Lasīsim tagad kādu jautru stāstu.",
        "Vilciens brauc ātri pa sliedēm.",
        "Es varu ļoti ātri saskaitīt līdz desmit.",
    ],
    "mg": [
        "Nipetraka teo amin'ny tatatra mafana ny saka.",
        "Tia mihazakazaka sy misabaka ary milalao aho.",
        "Jereo ny lanitra manga lehibe androany.",
        "Afaka mahazo baolina kely ny alikaiko.",
        "Mihinana paoma mena izahay aorian'ny sakafo.",
        "Mamirapiratra ary boribory ny volana amin'ny alina.",
        "Omeo ahy ny kaopy maitso azafady.",
        "Mihira hira faly ny vorona isan'andro maraina.",
        "Nandrina masoandro mavo sy hazo izy.",
        "Andao isika hamaky tantara mahafinaritra ankehitriny.",
        "Mihazakazaka haingana amin'ny lalamby ny fiara-mby.",
        "Mahay manisa hatramin'ny folo haingana aho.",
    ],
    "mi": [
        "I noho te ngeru i runga i te whāriki mahana.",
        "E pai ana ahau ki te oma, ki te peke, ki te tākaro.",
        "Titiro ki te rangi nui kahurangi ināianei.",
        "Ka taea e tōku kurī te hopu i te pōro iti.",
        "Ka kai mātou i ngā āporo whero i muri i te tina.",
        "He mārama, he porotaka te marama i te pō.",
        "Homai ki ahau te kapu kākāriki, tēnā koe.",
        "Ka waiata ngā manu i tētahi waiata harikoa ia ata.",
        "I tā ia i tētahi rā kōwhai me tētahi rākau.",
        "Me pānui tātou i tētahi kōrero ngahau ināianei.",
        "Ka tere haere te tereina i runga i ngā raina.",
        "Ka taea e ahau te tatau ki te tekau i tino tere.",
    ],
    "mk": [
        "Мачката седеше на топлата рогозка.",
        "Сакам да трчам, скокам и играм.",
        "Погледни го големото сино небо денес.",
        "Моето куче може да фати мала топка.",
        "По ручекот јадеме црвени јаболка.",
        "Ноќе месечината е светла и тркалезна.",
        "Ве молам, дај ми ја зелената чаша.",
        "Птиците пеат весела песна секое утро.",
        "Таа нацрта жолто сонце и дрво.",
        "Ајде сега да читаме забавна приказна.",
        "Возот оди брзо по пругата.",
        "Можам да бројам до десет многу брзо.",
    ],
    "ml": [
        "പൂച്ച ചൂടുള്ള പായയിൽ ഇരുന്നു.",
        "എനിക്ക് ഓടാനും ചാടാനും കളിക്കാനും ഇഷ്ടമാണ്.",
        "ഇന്ന് വലിയ നീല ആകാശം നോക്കൂ.",
        "എന്റെ നായ്ക്ക് ഒരു ചെറിയ പന്ത് പിടിക്കാൻ കഴിയും.",
        "ഉച്ചഭക്ഷണത്തിന് ശേഷം ഞങ്ങൾ ചുവന്ന ആപ്പിൾ കഴിക്കും.",
        "രാത്രിയിൽ ചന്ദ്രൻ തിളക്കമുള്ളതും വൃത്താകൃതിയിലുള്ളതുമാണ്.",
        "ദയവായി എനിക്ക് പച്ച കപ്പ് തരൂ.",
        "പക്ഷികൾ എല്ലാ പ്രഭാതവും ഒരു സന്തോഷ ഗാനം പാടും.",
        "അവൾ ഒരു മഞ്ഞ സൂര്യനും ഒരു മരവും വരച്ചു.",
        "നമ്മൾ ഇപ്പോൾ ഒരു രസകരമായ കഥ വായിക്കാം.",
        "തീവണ്ടി ട്രാക്കിൽ വേഗത്തിൽ ഓടുന്നു.",
        "എനിക്ക് പത്ത് വരെ വളരെ വേഗത്തിൽ എണ്ണാൻ കഴിയും.",
    ],
    "mn": [
        "Муур дулаан дэвсгэр дээр суув.",
        "Би гүйх, үсрэх, тоглох дуртай.",
        "Өнөөдөр том цэнхэр тэнгэрийг хар.",
        "Миний нохой жижиг бөмбөгийг барьж чадна.",
        "Бид үдийн хоолны дараа улаан алим иддэг.",
        "Шөнө сар гэрэлтэй, дугуй байдаг.",
        "Надад ногоон аягыг өгнө үү.",
        "Шувууд өглөө бүр хөгжилтэй дуу дуулдаг.",
        "Тэр шар нар болон мод зурав.",
        "Одоо хөгжилтэй түүх уншицгаая.",
        "Галт тэрэг замаар хурдан явна.",
        "Би арав хүртэл маш хурдан тоолж чадна.",
    ],
    "mr": [
        "मांजर उबदार सतरंजीवर बसली.",
        "मला धावणे, उड्या मारणे आणि खेळणे आवडते.",
        "आज मोठ्या निळ्या आकाशाकडे बघ.",
        "माझा कुत्रा एक छोटा चेंडू पकडू शकतो.",
        "आम्ही जेवणानंतर लाल सफरचंद खातो.",
        "रात्री चंद्र तेजस्वी आणि गोल असतो.",
        "कृपया मला हिरवा कप दे.",
        "पक्षी दर सकाळी आनंदाचे गाणे गातात.",
        "तिने पिवळा सूर्य आणि एक झाड काढले.",
        "आता एक मजेदार गोष्ट वाचूया.",
        "आगगाडी रुळावरून वेगाने जाते.",
        "मी खूप वेगाने दहापर्यंत मोजू शकतो.",
    ],
    "ms": [
        "Kucing itu duduk di atas tikar yang hangat.",
        "Saya suka berlari, melompat dan bermain.",
        "Lihat langit biru yang luas hari ini.",
        "Anjing saya boleh menangkap bola kecil.",
        "Kami makan epal merah selepas makan tengah hari.",
        "Bulan kelihatan cerah dan bulat pada waktu malam.",
        "Tolong bagi saya cawan hijau itu.",
        "Burung-burung menyanyikan lagu gembira setiap pagi.",
        "Dia melukis matahari kuning dan sebatang pokok.",
        "Mari kita baca cerita yang seronok sekarang.",
        "Kereta api bergerak pantas di atas landasan.",
        "Saya boleh mengira sehingga sepuluh dengan sangat pantas.",
    ],
    "mt": [
        "Il-qattus poġġa fuq it-tapit sħun.",
        "Inħobb niġri u naqbeż u nilgħab.",
        "Ħares lejn is-sema blu kbir illum.",
        "Il-kelb tiegħi jista' jaqbad ballun żgħir.",
        "Nieklu tuffieħ aħmar wara l-pranzu.",
        "Il-qamar huwa dija u tond billejl.",
        "Jekk jogħġbok, agħtini l-kikkra ħadra.",
        "L-għasafar jgħannu għanja ferrieħa kull filgħodu.",
        "Hija għamlet xemx isfar u siġra.",
        "Ejja naqraw stejjer sabiħa issa.",
        "It-tren isuq malajr fuq il-binarji.",
        "Nista' ngħodd sa għaxra malajr ħafna.",
    ],
    "my": [
        "ကြောင်သည် နွေးသောခင်းကျင်းပေါ်မှာ ထိုင်နေသည်။",
        "ကျွန်တော် ပြေးခုန်ကစားတာကို နှစ်သက်သည်။",
        "ယနေ့ မိုးကောင်းကင်ကြီး နီလာရောင်ကို ကြည့်ပါ။",
        "ကျွန်တော်၏ ခွေးသည် သေးငယ်သောဘောလုံးကို ဖမ်းနိုင်သည်။",
        "ကျွန်တော်တို့ နေ့လည်စာပြီးနောက် အနီရောင်ပန်းသီးများကို စားသည်။",
        "ညဘက်တွင် လသည် တောက်ပပြီး အဝိုင်းပုံဖြစ်သည်။",
        "ကျေးဇူးပြု၍ အစိမ်းရောင်ခွက်ကို ပေးပါ။",
        "ငှက်များသည် နံနက်တိုင်း ပျော်ရွှင်သောသီချင်းကို ဆိုကြသည်။",
        "သူမသည် အဝါရောင်နေနှင့် သစ်ပင်တစ်ပင်ကို ရေဆွဲသည်။",
        "ယခု ပျော်စရာဇာတ်လမ်းတစ်ပုဒ် ဖတ်ကြစို့။",
        "ရထားသည် ရထားလမ်းကြောင်းတလျှောက် မြန်မြန်ဆန်ဆန် သွားသည်။",
        "ကျွန်တော် တစ်ဆယ်အထိ အလွန်မြန်မြန် ရေတွက်နိုင်သည်။",
    ],
    "ne": [
        "बिरालो तातो गुन्द्रीमा बस्यो।",
        "मलाई दौड्न, उफ्रन र खेल्न मन पर्छ।",
        "आज ठूलो निलो आकाश हेर।",
        "मेरो कुकुरले सानो बल समात्न सक्छ।",
        "हामी खाना खाएपछि रातो स्याउ खान्छौं।",
        "रातमा चन्द्रमा उज्यालो र गोलो हुन्छ।",
        "कृपया मलाई हरियो कप दिनुस्।",
        "चराहरू प्रत्येक बिहान खुसीको गीत गाउँछन्।",
        "उनले पहेँलो घाम र रूख बनाइन्।",
        "अब एउटा रमाइलो कथा पढौं।",
        "रेलगाडी पटरीमा छिटो जान्छ।",
        "म धेरै छिटो दसम्म गन्न सक्छु।",
    ],
    "nl": [
        "De kat zat op de warme mat.",
        "Ik ren, spring en speel graag.",
        "Kijk naar de grote blauwe lucht vandaag.",
        "Mijn hond kan een kleine bal vangen.",
        "We eten rode appels na de lunch.",
        "'s Nachts is de maan helder en rond.",
        "Geef me alsjeblieft de groene beker.",
        "Vogels zingen elke ochtend een vrolijk liedje.",
        "Ze tekende een gele zon en een boom.",
        "Laten we nu een leuk verhaal lezen.",
        "De trein rijdt snel over het spoor.",
        "Ik kan heel snel tot tien tellen.",
    ],
    "nn": [
        "Katten sat på den varme matta.",
        "Eg likar å springa og hoppa og leika.",
        "Sjå på den store blå himmelen i dag.",
        "Hunden min kan fanga ein liten ball.",
        "Vi et raude eple etter lunsj.",
        "Månen er lys og rund om natta.",
        "Ver snill å gje meg den grøne koppen.",
        "Fuglar syng ein glad song kvar morgon.",
        "Ho teikna ei gul sol og eit tre.",
        "La oss lesa ei morosam historie no.",
        "Toget går fort nedover sporet.",
        "Eg kan tella til ti veldig fort.",
    ],
    "no": [
        "Katten satt på den varme matten.",
        "Jeg liker å løpe, hoppe og leke.",
        "Se på den store blå himmelen i dag.",
        "Hunden min kan fange en liten ball.",
        "Vi spiser røde epler etter lunsj.",
        "Månen er lys og rund om natten.",
        "Kan du gi meg den grønne koppen?",
        "Fugler synger en glad sang hver morgen.",
        "Hun tegnet en gul sol og et tre.",
        "La oss lese en morsom historie nå.",
        "Toget går fort nedover sporet.",
        "Jeg kan telle til ti veldig fort.",
    ],
    "oc": [
        "Lo gat s'es assetat sus la catife cauda.",
        "M'agrada córrer, saltar e jogar.",
        "Mira lo grand cèl blau d'uèi.",
        "Mon chèn pòt agafar una boleta petita.",
        "Manjam de pomas rojas après lo dinnar.",
        "La luna es clara e redonda la nuèch.",
        "Passa'm la tassa verda, se te plai.",
        "Los ausèls cànton una cançon joiosa cada matin.",
        "Ela a desenhat un solelh jaune e un arbre.",
        "Legèm una istòria divertenta ara.",
        "Lo tren vai lèu per la via.",
        "Pòdi comptar fins a dètz fòrça lèu.",
    ],
    "pa": [
        "ਬਿੱਲੀ ਗਰਮ ਦਰੀ ਉੱਤੇ ਬੈਠ ਗਈ।",
        "ਮੈਨੂੰ ਦੌੜਨਾ, ਛਾਲ ਮਾਰਨਾ ਅਤੇ ਖੇਡਣਾ ਪਸੰਦ ਹੈ।",
        "ਅੱਜ ਵੱਡੇ ਨੀਲੇ ਅਸਮਾਨ ਵੱਲ ਵੇਖੋ।",
        "ਮੇਰਾ ਕੁੱਤਾ ਇੱਕ ਛੋਟੀ ਗੇਂਦ ਫੜ ਸਕਦਾ ਹੈ।",
        "ਅਸੀਂ ਦੁਪਹਿਰ ਦੇ ਖਾਣੇ ਤੋਂ ਬਾਅਦ ਲਾਲ ਸੇਬ ਖਾਂਦੇ ਹਾਂ।",
        "ਰਾਤ ਨੂੰ ਚੰਦ ਚਮਕਦਾਰ ਅਤੇ ਗੋਲ ਹੁੰਦਾ ਹੈ।",
        "ਕਿਰਪਾ ਕਰਕੇ ਮੈਨੂੰ ਹਰਾ ਕੱਪ ਦਿਓ।",
        "ਪੰਛੀ ਹਰ ਸਵੇਰੇ ਖੁਸ਼ੀ ਦਾ ਗੀਤ ਗਾਉਂਦੇ ਹਨ।",
        "ਉਸਨੇ ਪੀਲਾ ਸੂਰਜ ਅਤੇ ਇੱਕ ਰੁੱਖ ਬਣਾਇਆ।",
        "ਚਲੋ ਹੁਣ ਇੱਕ ਮਜ਼ੇਦਾਰ ਕਹਾਣੀ ਪੜ੍ਹੀਏ।",
        "ਰੇਲ ਗੱਡੀ ਪਟੜੀ ਉੱਤੇ ਤੇਜ਼ ਜਾਂਦੀ ਹੈ।",
        "ਮੈਂ ਬਹੁਤ ਤੇਜ਼ੀ ਨਾਲ ਦਸ ਤੱਕ ਗਿਣ ਸਕਦਾ ਹਾਂ।",
    ],
    "pl": [
        "Kot siedział na ciepłej macie.",
        "Lubię biegać, skakać i bawić się.",
        "Popatrz na duże niebieskie niebo dzisiaj.",
        "Mój pies potrafi złapać małą piłeczkę.",
        "Jemy czerwone jabłka po obiedzie.",
        "W nocy księżyc jest jasny i okrągły.",
        "Proszę, podaj mi zielony kubek.",
        "Ptaki śpiewają radosną piosenkę każdego ranka.",
        "Narysowała żółte słońce i drzewo.",
        "Przeczytajmy teraz zabawną historię.",
        "Pociąg jedzie szybko po torach.",
        "Potrafię liczyć do dziesięciu bardzo szybko.",
    ],
    "ps": [
        "پیشو د ګرمو بوریا پر ناسته وه.",
        "زه د منډو، ټوپونو او لوبو خوند اخلم.",
        "نن د لوی نیلي اسمان ته وګوره.",
        "زما سپی کولای شي یو کوچنی بال ونیسي.",
        "موږ د غرمې وروسته سور مڼه خورو.",
        "سپوږمۍ شپه کې روښانه او ګرده وي.",
        "مهرباني وکړه ماته شنه پیاله راکړه.",
        "مرغان هره سهار خوشاله سندره وایي.",
        "هغې د ژیړ لمر او ونې انځور کاږه.",
        "راځئ چې اوس یوه ساتیري کیسه ولولو.",
        "ریل ګاډی د پټلۍ سره چټک روان دی.",
        "زه کولای شم تر لسو ډیر چټک شمیرم.",
    ],
    "pt": [
        "O gato sentou no tapete morno.",
        "Eu gosto de correr, pular e brincar.",
        "Olha o grande céu azul hoje.",
        "Meu cachorro consegue pegar uma bolinha.",
        "Comemos maçãs vermelhas depois do almoço.",
        "À noite, a lua é brilhante e redonda.",
        "Por favor, me passe o copo verde.",
        "Os pássaros cantam uma canção alegre toda manhã.",
        "Ela desenhou um sol amarelo e uma árvore.",
        "Vamos ler uma história divertida agora.",
        "O trem vai rápido pelos trilhos.",
        "Eu consigo contar até dez muito rápido.",
    ],
    "ro": [
        "Pisica stătea pe covorul cald.",
        "Îmi place să alerg, să sar și să mă joc.",
        "Privește cerul mare și albastru azi.",
        "Câinele meu poate prinde o minge mică.",
        "Mâncăm mere roșii după prânz.",
        "Luna este strălucitoare și rotundă noaptea.",
        "Te rog, dă-mi cana verde.",
        "Păsările cântă un cântec vesel în fiecare dimineață.",
        "Ea a desenat un soare galben și un copac.",
        "Hai să citim o poveste amuzantă acum.",
        "Trenul merge repede pe șine.",
        "Pot să număr până la zece foarte repede.",
    ],
    "ru": [
        "Кошка сидела на тёплом коврике.",
        "Я люблю бегать, прыгать и играть.",
        "Посмотри на большое голубое небо сегодня.",
        "Мой пёс умеет ловить маленький мяч.",
        "Мы едим красные яблоки после обеда.",
        "Ночью луна яркая и круглая.",
        "Пожалуйста, передай мне зелёную кружку.",
        "Птицы поют весёлую песню каждое утро.",
        "Она нарисовала жёлтое солнце и дерево.",
        "Давайте сейчас прочитаем весёлую историю.",
        "Поезд быстро едет по рельсам.",
        "Я умею очень быстро считать до десяти.",
    ],
    "sa": [
        "बिडालः उष्णे आसने उपविष्टः।",
        "मम धावनम् उत्प्लवनम् क्रीडनं च रोचते।",
        "अद्य विशालम् नीलम् आकाशं पश्य।",
        "मम श्वा लघुकन्दुकं धर्तुं शक्नोति।",
        "वयं मध्याह्नभोजनानन्तरं रक्तानि फलानि खादामः।",
        "रात्रौ चन्द्रः दीप्तः वृत्तश्च अस्ति।",
        "कृपया मह्यं हरितं चषकं देहि।",
        "प्रत्येकं प्रातः खगाः आनन्दमयं गीतं गायन्ति।",
        "सा पीतं सूर्यम् वृक्षं च अचित्रयत्।",
        "अधुना वयम् एकां मनोरञ्जककथां पठाम।",
        "रेलयानम् मार्गे वेगेन गच्छति।",
        "अहम् दशपर्यन्तम् अतिशीघ्रम् गणयितुं शक्नोमि।",
    ],
    "sd": [
        "ٻلي گرم مادي تي ويٺي.",
        "مونکي ڊوڙڻ، ٽپو ڏيڻ ۽ راند ڪرڻ پسند آهي.",
        "اڄ وڏي نيري آسمان ڏانهن ڏسو.",
        "منهنجو ڪتو هڪ ننڍي گيند کي پڪڙي سگهي ٿو.",
        "اسين ماني کانپوءِ ڳاڙها سيب کائيندا آهيون.",
        "چنڊ رات جو روشن ۽ گول هوندو آهي.",
        "مهرباني ڪري مونکي سائي پيالي ڏيو.",
        "پکي هر صبح خوشيءَ جو گيت ڳائيندا آهن.",
        "هن هڪ پيلو سج ۽ هڪ وڻ ٺاهيو.",
        "اچو ته هاڻي هڪ دلچسپ ڪهاڻي پڙهون.",
        "ريل گاڏي پٽڙي تي تيزيءَ سان هلندي آهي.",
        "مان ڏاڍي تيزيءَ سان ڏهن تائين ڳڻي سگهان ٿو.",
    ],
    "si": [
        "පූසා උණුසුම් ඇතිරිල්ල මත ඉදගත්තා.",
        "මම දුවන්නට, පනින්නට සහ සෙල්ලම් කරන්නට කැමතියි.",
        "අද විශාල නිල් අහසට බලන්න.",
        "මගේ බල්ලාට කුඩා බෝලයක් අල්ලා ගත හැකියි.",
        "අපි දිවා ආහාරයෙන් පසු රතු ඇපල් කනවා.",
        "රාත්‍රියේ සඳු දීප්තිමත් හා රවුම් ය.",
        "කරුණාකර මට කොළ කෝප්පය දෙන්න.",
        "කුරුල්ලෝ සෑම උදෑසනක්ම සතුටු ගීතයක් ගයති.",
        "ඇය කහ හිරු සහ ගසක් ඇඳුවා.",
        "දැන් විනෝදජනක කතාවක් කියවමු.",
        "දුම්රිය මාර්ගය ඔස්සේ ඉක්මනින් යයි.",
        "මට ඉතා ඉක්මනින් දහය දක්වා ගණන් කළ හැකියි.",
    ],
    "sk": [
        "Mačka sedela na teplej rohožke.",
        "Rád bežím, skáčem a hrám sa.",
        "Pozri sa na veľkú modrú oblohu dnes.",
        "Môj pes vie chytiť malú loptičku.",
        "Po obede jeme červené jablká.",
        "V noci je mesiac jasný a okrúhly.",
        "Podaj mi prosím zelený hrnček.",
        "Vtáky každé ráno spievajú radostnú pieseň.",
        "Nakreslila žlté slnko a strom.",
        "Prečítajme si teraz zábavný príbeh.",
        "Vlak ide rýchlo po koľajniciach.",
        "Viem veľmi rýchlo počítať do desať.",
    ],
    "sl": [
        "Mačka je sedela na topli preprogi.",
        "Rad tečem, skačem in se igram.",
        "Poglej na veliko modro nebo danes.",
        "Moj pes lahko ujame majhno žogo.",
        "Po kosilu jemo rdeča jabolka.",
        "Ponoči je luna svetla in okrogla.",
        "Prosim, podaj mi zeleno skodelico.",
        "Ptice vsako jutro pojejo veselo pesem.",
        "Narisala je rumeno sonce in drevo.",
        "Preberimo si zdaj zabavno zgodbo.",
        "Vlak hitro drsi po tirih.",
        "Znam šteti do deset zelo hitro.",
    ],
    "sn": [
        "Katsi yakagara parutsago rinodziya.",
        "Ndinoda kumhanya, kubhururuka uye kutamba.",
        "Tarisa denga guru rebhuruu nhasi.",
        "Imbwa yangu inogona kubata bhora diki.",
        "Tinodya mapupu akatsvuka mushure mekudya kwemanheru.",
        "Mwedzi unopenya uye wakatenderera usiku.",
        "Ndapota ndipase kapu yechisvio.",
        "Shiri dzinoima rwiyo rwomufaro mangwanani ose.",
        "Akaveza zuva reyero nemuti.",
        "Ngatiwerenga nyaya inofadza izvozvi.",
        "Chitima chinofamba nekukurumidza pamuchinjiko.",
        "Ndinogona kuverenga kusvika gumi nekukurumidza kwazvo.",
    ],
    "so": [
        "Bisaddu waxay fadhiisatay xeedka kulul.",
        "Waxaan jecelahay orodka, boodidda iyo ciyaarista.",
        "Eeg samooyinka buluugga ee waaweyn maanta.",
        "Eeyahaygu wuxuu qaban karaa kubadda yar.",
        "Waxaan cunaa tufaaxa cas ka dib qadada.",
        "Dayaxu waa dhalaalayaa oo wareegsan habeenkii.",
        "Fadlan ii sii koobka cagaaran.",
        "Shimbirahu waxay heesaan heesta farxadda subax kasta.",
        "Waxay sawirtay qorraxda jaalle iyo geed.",
        "Aan hadda akhrino sheekada xiisaha leh.",
        "Tareenku wuxuu u socdaa xawli korkiisa.",
        "Waxaan ku kari karaa in aan tiriyaa ilaa toban si dhakhso ah.",
    ],
    "sr": [
        "Мачка је седела на топлој простирци.",
        "Волим да трчим, скачем и играм се.",
        "Погледај велико плаво небо данас.",
        "Мој пас може да ухвати малу лоптицу.",
        "Ми једемо црвене јабуке после ручка.",
        "Ноћу је месец светао и округао.",
        "Молим те, додај ми зелену шољицу.",
        "Птице сваког јутра певају срећну песму.",
        "Она је нацртала жуто сунце и дрво.",
        "Хајде да сада читамо забавну причу.",
        "Воз брзо иде по шинама.",
        "Могу врло брзо да бројим до десет.",
    ],
    "sq": [
        "Macja u ul mbi rrogozin e ngrohtë.",
        "Më pëlqen të vrapoj, të kërcej dhe të luaj.",
        "Shiko qiellin e madh blu sot.",
        "Qeni im mund të kapë një top të vogël.",
        "Ne hamë mollë të kuqe pas drekës.",
        "Hëna është e ndritshme dhe e rrumbullakët natën.",
        "Të lutem, ma jep gotën e gjelbër.",
        "Zogjtë këndojnë një këngë të gëzueshme çdo mëngjes.",
        "Ajo vizatoi një diell të verdhë dhe një pemë.",
        "Hajde të lexojmë një histori argëtuese tani.",
        "Treni shkon shpejt nëpër binarë.",
        "Unë mund të numëroj deri në dhjetë shumë shpejt.",
    ],
    "su": [
        "Ucing calik dina samak anu haneut.",
        "Abdi resep lumpat, luncat, jeung ulin.",
        "Tingali langit biru anu ageung ayeuna.",
        "Anjing abdi tiasa nangkep bal leutik.",
        "Urang tuang apel beureum saatos tuang siang.",
        "Bulan caang jeung buleud peuting.",
        "Punten, pasihan abdi cangkir héjo.",
        "Manuk ngahaleuang lagu gumbira unggal isuk.",
        "Anjeunna ngagambar panonpoé konéng jeung tangkal.",
        "Hayu urang maca carita seru ayeuna.",
        "Kareta lumpat gancang dina rel.",
        "Abdi tiasa ngitung dugi ka sapuluh kalayan gancang.",
    ],
    "sv": [
        "Katten satt på den varma mattan.",
        "Jag gillar att springa och hoppa och leka.",
        "Titta på den stora blå himlen idag.",
        "Min hund kan fånga en liten boll.",
        "Vi äter röda äpplen efter lunch.",
        "Månen är ljus och rund på natten.",
        "Kan du räcka mig den gröna koppen?",
        "Fåglarna sjunger en glad sång varje morgon.",
        "Hon ritade en gul sol och ett träd.",
        "Låt oss läsa en rolig berättelse nu.",
        "Tåget går fort längs spåret.",
        "Jag kan räkna till tio väldigt snabbt.",
    ],
    "sw": [
        "Paka alikaa kwenye mkeka wa joto.",
        "Napenda kukimbia, kuruka na kucheza.",
        "Angalia anga kubwa la bluu leo.",
        "Mbwa wangu anaweza kukamata mpira mdogo.",
        "Tunakula tofaa nyekundu baada ya chakula cha mchana.",
        "Mwezi ni angavu na mviringo usiku.",
        "Tafadhali nipe kikombe cha kijani.",
        "Ndege wanaimba wimbo wa furaha kila asubuhi.",
        "Alichora jua la njano na mti.",
        "Hebu tusomе hadithi ya kufurahisha sasa.",
        "Treni inakwenda haraka kwenye reli.",
        "Ninaweza kuhesabu hadi kumi haraka sana.",
    ],
    "ta": [
        "பூனை வெப்பமான பாயில் அமர்ந்தது.",
        "நான் ஓடவும், குதிக்கவும், விளையாடவும் விரும்புகிறேன்.",
        "இன்று பெரிய நீல வானத்தை பாருங்கள்.",
        "என் நாய் ஒரு சிறிய பந்தை பிடிக்கும்.",
        "நாங்கள் மதிய உணவிற்கு பிறகு சிவந்த ஆப்பிள்கள் சாப்பிடுகிறோம்.",
        "இரவில் நிலா பிரகாசமாகவும் வட்டமாகவும் இருக்கிறது.",
        "தயவுசெய்து பச்சை கோப்பையை எனக்கு கொடுங்கள்.",
        "பறவைகள் ஒவ்வொரு காலையிலும் மகிழ்ச்சியான பாட்டு பாடுகின்றன.",
        "அவள் ஒரு மஞ்சள் சூரியனையும் ஒரு மரத்தையும் வரைந்தாள்.",
        "நாம் இப்போது ஒரு வேடிக்கையான கதை படிப்போம்.",
        "ரயில் தண்டவாளத்தில் வேகமாக செல்கிறது.",
        "நான் பத்து வரை மிகவும் வேகமாக எண்ண முடியும்.",
    ],
    "te": [
        "పిల్లి వెచ్చటి చాపమీద కూర్చుంది.",
        "నాకు పరుగు పెట్టడం, గంతులు వేయడం, ఆడడం ఇష్టం.",
        "ఈరోజు పెద్ద నీలి ఆకాశాన్ని చూడు.",
        "నా కుక్క చిన్న బంతిని పట్టుకోగలదు.",
        "మేము భోజనం తర్వాత ఎర్రటి ఆపిల్లు తింటాం.",
        "రాత్రి చంద్రుడు తేజస్వంతంగా మరియు గుండ్రంగా ఉంటాడు.",
        "దయచేసి నాకు పచ్చని కప్పు అందివ్వు.",
        "పక్షులు ప్రతి ఉదయం సంతోషమైన పాట పాడతాయి.",
        "ఆమె పసుపు రంగు సూర్యుడిని మరియు ఒక చెట్టు గీసింది.",
        "ఇప్పుడు మనం ఒక సరదా కథ చదువుదాం.",
        "రైలు పట్టాల మీద వేగంగా వెళ్తుంది.",
        "నేను చాలా వేగంగా పది వరకు లెక్కించగలను.",
    ],
    "tg": [
        "Гурба дар фарши гарм нишаст.",
        "Ман дӯст медорам, ки давам, ҷаҳам ва бозӣ кунам.",
        "Имрӯз ба осмони калони кабуд нигоҳ кун.",
        "Саги ман метавонад тӯби хурдро гирад.",
        "Мо баъд аз нисфирӯзӣ себи сурх мехӯрем.",
        "Шаб моҳ равшан ва мудаввар аст.",
        "Лутфан пиёлаи сабзро ба ман бидеҳ.",
        "Паррандагон ҳар субҳ суруди хушҳолӣ мехонанд.",
        "Вай офтоби зарду дарахтеро кашид.",
        "Биёед ҳоло як ҳикояи шавқоварро хонем.",
        "Қатора аз рӯи роҳ зуд мегузарад.",
        "Ман метавонам то даҳ хеле зуд ҳисоб кунам.",
    ],
    "th": [
        "แมวนั่งอยู่บนเสื่อที่อบอุ่น",
        "ฉันชอบวิ่ง กระโดด และเล่น",
        "ดูท้องฟ้าสีฟ้าที่กว้างใหญ่วันนี้",
        "สุนัขของฉันสามารถจับลูกบอลเล็กๆ ได้",
        "เรากินแอปเปิ้ลแดงหลังอาหารกลางวัน",
        "ดวงจันทร์สว่างและกลมในยามค่ำคืน",
        "กรุณาส่งแก้วสีเขียวให้ฉันด้วย",
        "นกร้องเพลงสนุกทุกเช้า",
        "เธอวาดดวงอาทิตย์สีเหลืองและต้นไม้",
        "มาอ่านนิทานสนุกกันเดี๋ยวนี้เลย",
        "รถไฟวิ่งเร็วไปตามรางรถไฟ",
        "ฉันนับได้ถึงสิบได้อย่างรวดเร็วมาก",
    ],
    "tk": [
        "Pişik ýyly hala üstünde oturdy.",
        "Men ylgamaklygy, bökmekligi we oýnamaklygy gowy görýärin.",
        "Bu gün uly gök asmana bak.",
        "Meniň itim kiçijik topy tutup bilýär.",
        "Biz nahardan soň gyzyl alma iýýäris.",
        "Gijelerine Aý ýagty we tegelek.",
        "Hanha, maňa ýaşyl käse ber.",
        "Guşlar her säher şatlykly aýdym aýdýar.",
        "Ol sary gün we agaç çyzdy.",
        "Geliň, indi gyzykly hekaýa okalyň.",
        "Otly demir ýol boýunça çalt gidýär.",
        "Men onа çenli gaty çalt saýap bilýärin.",
    ],
    "tl": [
        "Ang pusa ay umupo sa mainit na banig.",
        "Gusto ko ang tumakbo, lumukso, at maglaro.",
        "Tingnan ang malaking asul na langit ngayon.",
        "Ang aking aso ay makakahuli ng maliit na bola.",
        "Kumakain kami ng mga pulang mansanas pagkatapos ng tanghalian.",
        "Ang buwan ay maliwanag at bilog sa gabi.",
        "Pakiabot mo sa akin ang berdeng tasa.",
        "Ang mga ibon ay umawit ng masayang kanta tuwing umaga.",
        "Gumuhit siya ng dilaw na araw at isang puno.",
        "Magbasa tayo ng masayang kwento ngayon.",
        "Ang tren ay mabilis na tumatakbo sa riles.",
        "Mabilis akong makabibilang hanggang sampu.",
    ],
    "tr": [
        "Kedi sıcak minderin üzerinde oturdu.",
        "Koşmayı, zıplamayı ve oynamayı seviyorum.",
        "Bugün büyük mavi gökyüzüne bak.",
        "Köpeğim küçük bir topu yakalayabilir.",
        "Öğle yemeğinden sonra kırmızı elma yeriz.",
        "Ay geceleri parlak ve yuvarlaktır.",
        "Lütfen yeşil bardağı uzatır mısın?",
        "Kuşlar her sabah neşeli bir şarkı söyler.",
        "O sarı bir güneş ve bir ağaç çizdi.",
        "Haydi şimdi eğlenceli bir hikaye okuyalım.",
        "Tren raylar boyunca hızla gider.",
        "On'a kadar çok hızlı sayabiliyorum.",
    ],
    "tt": [
        "Мәче йылы паласта утырды.",
        "Мин йөгерергә, сикерергә һәм уйнарга яратам.",
        "Бүген зур зәңгәр күккә кара.",
        "Минем этем кечкенә туп тота ала.",
        "Без төштән соң кызыл алма ашыйбыз.",
        "Кичен ай якты һәм түгәрәк.",
        "Зинһар, яшел чашканы миңа бир.",
        "Кошлар иртән саен шат җыр җырлый.",
        "Ул сары кояш һәм агач сызды.",
        "Без хәзер кызыклы хикәя укыйк.",
        "Поезд рельслар буйлап тиз бара.",
        "Мин унга кадәр бик тиз санай алам.",
    ],
    "uk": [
        "Кіт сидів на теплому килимку.",
        "Я люблю бігати, стрибати і гратися.",
        "Подивись на велике синє небо сьогодні.",
        "Мій пес може зловити маленький м'яч.",
        "Ми їмо червоні яблука після обіду.",
        "Місяць вночі яскравий і круглий.",
        "Будь ласка, передай мені зелену чашку.",
        "Птахи щоранку співають веселу пісню.",
        "Вона намалювала жовте сонце і дерево.",
        "Давайте зараз прочитаємо цікаву казку.",
        "Потяг швидко їде по рейках.",
        "Я можу порахувати до десяти дуже швидко.",
    ],
    "ur": [
        "بلی گرم چٹائی پر بیٹھی۔",
        "مجھے دوڑنا، کودنا اور کھیلنا پسند ہے۔",
        "آج بڑے نیلے آسمان کو دیکھو۔",
        "میرا کتا چھوٹی سی گیند پکڑ سکتا ہے۔",
        "ہم دوپہر کے کھانے کے بعد سرخ سیب کھاتے ہیں۔",
        "رات کو چاند روشن اور گول ہوتا ہے۔",
        "براہ کرم مجھے سبز کپ دیں۔",
        "پرندے ہر صبح خوش کن گیت گاتے ہیں۔",
        "اس نے ایک پیلا سورج اور ایک درخت بنایا۔",
        "آؤ ابھی ایک مزے دار کہانی پڑھتے ہیں۔",
        "ٹرین پٹری پر تیزی سے جاتی ہے۔",
        "میں دس تک بہت تیزی سے گن سکتا ہوں۔",
    ],
    "uz": [
        "Mushuk iliq gilamcha ustida o'tirdi.",
        "Men yugurishni, sakrashni va o'ynashni yaxshi ko'raman.",
        "Bugun katta ko'k osmonga qara.",
        "Mening itim kichik to'pni tuta oladi.",
        "Biz tushdan keyin qizil olma yeymiz.",
        "Oy kechasi yorqin va yumaloq.",
        "Iltimos, menga yashil piyolani uzating.",
        "Qushlar har ertalab quvnoq qo'shiq aytishadi.",
        "U sariq quyosh va daraxt chizdi.",
        "Keling, hozir qiziqarli hikoya o'qiylik.",
        "Poyezd yo'lda tez yuradi.",
        "Men o'ngacha juda tez sana olaman.",
    ],
    "vi": [
        "Con mèo ngồi trên tấm thảm ấm.",
        "Tôi thích chạy, nhảy và chơi.",
        "Hãy nhìn bầu trời xanh rộng lớn hôm nay.",
        "Con chó của tôi có thể bắt một quả bóng nhỏ.",
        "Chúng tôi ăn táo đỏ sau bữa trưa.",
        "Mặt trăng sáng và tròn vào ban đêm.",
        "Làm ơn đưa cho tôi cái cốc màu xanh.",
        "Những con chim hót bài ca vui vẻ mỗi buổi sáng.",
        "Cô ấy vẽ một mặt trời màu vàng và một cái cây.",
        "Chúng ta hãy đọc một câu chuyện vui ngay bây giờ.",
        "Tàu hỏa đi nhanh trên đường ray.",
        "Tôi có thể đếm đến mười rất nhanh.",
    ],
    "yi": [
        "די קאַץ האָט געזעסן אויף דעם וואַרעמן מאַט.",
        "איך מאַג לויפן און שפּרינגען און שפּילן.",
        "קוק אויף דעם גרויסן בלויען הימל הייַנט.",
        "מיין הונט קען כאַפּן אַ קליין באָל.",
        "מיר עסן רויטע עפּל נאָך מיטאָג.",
        "דער לבנה איז העל און רונד בייַ נאַכט.",
        "ביטע גיב מיר דעם גרינעם כּוס.",
        "פייגלען זינגען אַ פרייַלעכן ליד יעדן מאָרגן.",
        "זי האָט געמאָלט אַ געלע זון און אַ בוים.",
        "לאָמיר לייענען אַ שפּאַסיקע מעשׂה יעצט.",
        "דער צוג פאָרט שנעל אַראָפּ דעם שפּור.",
        "איך קען צײלן ביז צען זייער שנעל.",
    ],
    "yo": [
        "Ológbo jókòó lórí ìpele tó gbóná.",
        "Mo fẹ́ràn sísáré, fífo àti eré.",
        "Wo ojú ọ̀run nlá bùlúù lónì.",
        "Ajá mi lè mú bọọ̀lù kékeré.",
        "A jẹun àpùl pupa lẹ́yìn oúnjẹ ọsan.",
        "Òṣùpá dán mọ́rán, ó sì yípo ní alẹ́.",
        "Jọ̀wọ́ fún mi ní ife aláwọ̀ ewé.",
        "Àwọn ẹyẹ ń kọrin orin ayọ̀ gbogbo àárọ̀.",
        "Ó yà oòrùn ofeefee àti igi kan.",
        "Jẹ́ ká ka ìtàn tó wúni lára báyìí.",
        "Ọkọ̀ ojú irin máa ń sáré kánkán sórí ọ̀nà irin.",
        "Mo lè kà sí mẹ́wàá ní ìyára púpọ̀.",
    ],
    "zh": [
        "猫坐在温暖的垫子上。",
        "我喜欢跑步、跳跃和玩耍。",
        "今天看看那片湛蓝的天空。",
        "我的狗能接住一个小球。",
        "我们午饭后吃红苹果。",
        "夜晚的月亮又亮又圆。",
        "请把绿色的杯子递给我。",
        "鸟儿每天早晨唱着欢快的歌。",
        "她画了一个黄色的太阳和一棵树。",
        "我们现在来读一个有趣的故事吧。",
        "火车沿着轨道飞速行驶。",
        "我能很快地数到十。",
    ],
}

# When a language has no set yet, fall back to English so the flow never blocks.
_FALLBACK = "en"


def get_prompts(language: str | None = None, n: int | None = None) -> list[str]:
    """Return up to ``n`` karaoke sentences for ``language`` (English fallback)."""
    code = (language or _FALLBACK).strip().lower()[:2]
    sentences = PROMPT_SETS.get(code) or PROMPT_SETS[_FALLBACK]
    return sentences[:n] if n else list(sentences)


def available_languages() -> list[str]:
    return sorted(PROMPT_SETS)
